# Generated by Django 6.0 on 2026-01-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upated_at',
            new_name='updated_at',
        ),
    ]
